replicaCount: 2
image:
  repository: ahhammadi/k8s-hostname
  pullPolicy: Always
  tag: 1.6.0
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: k8s-hostname.ahmed-hammadi.com
    paths:
    - path: /
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
